import { existsSync, mkdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { generateKeypair, signRecordForExample } from './crypto.js';
import type { AttestationRecord } from './types.js';

export interface InitResult {
  targetDir: string;
  recordsFile: string;
  keypairFile: string;
  readmeFile: string;
}

/**
 * Scaffolds an example directory with a freshly generated Ed25519 keypair
 * and a handful of example attestation records -- some validly signed, some
 * intentionally broken (tampered payload, wrong key, malformed signature,
 * missing signature) -- so a new user can immediately run `verify`/`report`/
 * `dashboard` against real data and see both the verified and unverified
 * paths in action. This keypair and these records are example data only,
 * generated fresh on every `init` run -- never treat them as real
 * credentials or real compute usage.
 */
export function scaffoldExample(targetDir: string): InitResult {
  if (existsSync(targetDir)) {
    throw new Error(`${targetDir} already exists -- remove it or choose a different path before running init`);
  }
  mkdirSync(targetDir, { recursive: true });

  const keypair = generateKeypair();
  const wrongKeypair = generateKeypair();

  const baseIssuedAt = new Date();
  const isoAt = (offsetMinutes: number): string =>
    new Date(baseIssuedAt.getTime() + offsetMinutes * 60_000).toISOString();

  type UnsignedRecord = Omit<AttestationRecord, 'signature'>;

  const valid1: UnsignedRecord = {
    record_id: 'rec-001',
    issued_at: isoAt(0),
    provider: 'acme-cloud',
    hardware: '8xH100-SXM5',
    workload_type: 'training',
    compute_amount: 128,
    compute_unit: 'gpu_hours',
    issuer_public_key: keypair.publicKeyBase64,
  };
  const valid2: UnsignedRecord = {
    record_id: 'rec-002',
    issued_at: isoAt(10),
    provider: 'beta-compute',
    hardware: '4xA100-80GB',
    workload_type: 'inference',
    compute_amount: 12.5,
    compute_unit: 'gpu_hours',
    issuer_public_key: keypair.publicKeyBase64,
  };
  const valid3: UnsignedRecord = {
    record_id: 'rec-003',
    issued_at: isoAt(20),
    provider: 'acme-cloud',
    hardware: '8xH100-SXM5',
    workload_type: 'idle',
    compute_amount: 4,
    compute_unit: 'gpu_hours',
    issuer_public_key: keypair.publicKeyBase64,
  };

  const records: unknown[] = [];

  for (const rec of [valid1, valid2, valid3]) {
    const signature = signRecordForExample(rec, keypair.privateKeyBase64);
    records.push({ ...rec, signature });
  }

  // Tampered payload: sign one compute_amount, then ship a record claiming a
  // different one. The signature no longer matches the canonical payload.
  const tamperedBase: UnsignedRecord = {
    record_id: 'rec-004',
    issued_at: isoAt(30),
    provider: 'gamma-hpc',
    hardware: '2xH100-PCIe',
    workload_type: 'training',
    compute_amount: 10,
    compute_unit: 'gpu_hours',
    issuer_public_key: keypair.publicKeyBase64,
  };
  const tamperedSignature = signRecordForExample(tamperedBase, keypair.privateKeyBase64);
  records.push({ ...tamperedBase, compute_amount: 1000, signature: tamperedSignature });

  // Wrong key: signed by a different private key than the one whose public
  // key is embedded in the record.
  const wrongKeyBase: UnsignedRecord = {
    record_id: 'rec-005',
    issued_at: isoAt(40),
    provider: 'gamma-hpc',
    hardware: '2xH100-PCIe',
    workload_type: 'inference',
    compute_amount: 6,
    compute_unit: 'gpu_hours',
    issuer_public_key: keypair.publicKeyBase64,
  };
  const wrongKeySignature = signRecordForExample(wrongKeyBase, wrongKeypair.privateKeyBase64);
  records.push({ ...wrongKeyBase, signature: wrongKeySignature });

  // Malformed signature: valid base64, but the wrong length to be a real
  // Ed25519 signature at all.
  records.push({
    record_id: 'rec-006',
    issued_at: isoAt(50),
    provider: 'delta-cloud',
    hardware: '1xL40S',
    workload_type: 'unknown',
    compute_amount: 2,
    compute_unit: 'gpu_hours',
    issuer_public_key: keypair.publicKeyBase64,
    signature: 'QUJDRA==',
  });

  // Missing signature entirely: fails schema validation (required field),
  // never even reaches signature verification.
  records.push({
    record_id: 'rec-007',
    issued_at: isoAt(60),
    provider: 'delta-cloud',
    hardware: '1xL40S',
    workload_type: 'idle',
    compute_amount: 1,
    compute_unit: 'gpu_hours',
    issuer_public_key: keypair.publicKeyBase64,
  });

  const recordsFile = join(targetDir, 'records.jsonl');
  writeFileSync(recordsFile, records.map((r) => JSON.stringify(r)).join('\n') + '\n', 'utf-8');

  const keypairFile = join(targetDir, 'keypair.json');
  writeFileSync(
    keypairFile,
    JSON.stringify(
      {
        _comment:
          'Example keypair generated by `paceproof init` for demo purposes only. Never a real credential -- do not reuse for anything real.',
        public_key: keypair.publicKeyBase64,
        private_key: keypair.privateKeyBase64,
      },
      null,
      2,
    ) + '\n',
    'utf-8',
  );

  const readmeFile = join(targetDir, 'README.md');
  writeFileSync(
    readmeFile,
    [
      '# PaceProof example data',
      '',
      'Generated by `paceproof init`. This directory contains:',
      '',
      '- `keypair.json` -- a freshly generated Ed25519 example keypair (not a real credential).',
      '- `records.jsonl` -- 7 example attestation records: 3 validly signed, and 4 intentionally',
      '  broken to demonstrate every failure mode `verify`/`report` detect:',
      '  - `rec-004`: tampered payload (compute_amount changed after signing)',
      '  - `rec-005`: signed with the wrong key',
      '  - `rec-006`: malformed signature (wrong length)',
      '  - `rec-007`: missing signature field entirely (fails schema validation)',
      '',
      'Try:',
      '',
      '```',
      'paceproof report ./paceproof-example',
      'paceproof verify ./paceproof-example/records.jsonl',
      'paceproof dashboard ./paceproof-example --out ./paceproof-example/dashboard.html',
      '```',
      '',
    ].join('\n'),
    'utf-8',
  );

  return { targetDir, recordsFile, keypairFile, readmeFile };
}
