"""Renders a report as a single self-contained static HTML file.

Mirrors packages/cli-ts/src/dashboard.ts: inline CSS, no external requests of
any kind, no external scripts, no remote images or fonts. v0.1 ships a single
clean light theme -- no dark-mode toggle yet.
"""

from __future__ import annotations

import html as html_module

from .types import Report


def _fmt_num(n: float) -> str:
    return str(int(n)) if float(n).is_integer() else f"{n:.2f}"


def _provider_totals(report: Report) -> list[tuple[str, float, str]]:
    totals: list[tuple[str, float, str]] = []
    for provider, data in report["summary"]["by_provider"].items():
        for bucket in data["verified"]:
            totals.append((provider, bucket["compute_amount_total"], bucket["compute_unit"]))
    return sorted(totals, key=lambda t: t[1], reverse=True)


def render_dashboard_html(report: Report) -> str:
    totals = _provider_totals(report)
    max_total = max([1.0] + [t[1] for t in totals])

    bars_html = "\n".join(
        f"""
        <div class="bar-row">
          <div class="bar-label">{html_module.escape(provider)}</div>
          <div class="bar-track">
            <div class="bar-fill" style="width:{max(2, round((total / max_total) * 100))}%"></div>
          </div>
          <div class="bar-value">{html_module.escape(_fmt_num(total))} {html_module.escape(unit)}</div>
        </div>"""
        for provider, total, unit in totals
    )

    unverified_rows_html = "\n".join(
        "<tr><td>{}</td><td>{}</td></tr>".format(
            html_module.escape(entry["record_id"] or "(no record_id)"),
            html_module.escape(entry["reason"]),
        )
        for entry in report["summary"]["unverified_reasons"]
    )

    verified_units_html = "\n".join(
        f"<tr><td>{html_module.escape(unit)}</td><td>{html_module.escape(_fmt_num(total))}</td></tr>"
        for unit, total in report["summary"]["verified_compute_total_by_unit"].items()
    )

    unverified_units_html = "\n".join(
        f"<tr><td>{html_module.escape(unit)}</td><td>{html_module.escape(_fmt_num(total))}</td></tr>"
        for unit, total in report["summary"]["unverified_compute_total_by_unit"].items()
    )

    source = html_module.escape(report["source"])
    generated_at = html_module.escape(report["generated_at"])

    if unverified_rows_html:
        excluded_section_html = (
            "<table><thead><tr><th>record_id</th><th>reason</th></tr></thead>"
            f"<tbody>{unverified_rows_html}</tbody></table>"
        )
    else:
        excluded_section_html = '<div class="empty">every record verified</div>'

    footer_text = (
        "Generated by paceproof-cli. This report reflects only the records found at the given source; "
        "it is not a compliance or regulatory certification of any kind."
    )

    return f"""<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>PaceProof report -- {source}</title>
<style>
  :root {{
    color-scheme: light;
    --bg: #f7f7fa;
    --panel: #ffffff;
    --border: #e2e2e8;
    --text: #1a1a24;
    --muted: #6b6b76;
    --verified: #2e7d5b;
    --unverified: #b3452e;
    --accent: #3b5bdb;
  }}
  * {{ box-sizing: border-box; }}
  body {{
    margin: 0;
    padding: 2rem;
    background: var(--bg);
    color: var(--text);
    font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
    line-height: 1.5;
  }}
  h1 {{ font-size: 1.5rem; margin: 0 0 0.25rem; }}
  .meta {{ color: var(--muted); font-size: 0.9rem; margin-bottom: 1.5rem; }}
  .grid {{
    display: grid;
    grid-template-columns: repeat(auto-fit, minmax(260px, 1fr));
    gap: 1rem;
    margin-bottom: 1.5rem;
  }}
  .panel {{
    background: var(--panel);
    border: 1px solid var(--border);
    border-radius: 8px;
    padding: 1.25rem;
  }}
  .panel h2 {{ margin: 0 0 0.75rem; font-size: 1.05rem; }}
  .stat {{ font-size: 2rem; font-weight: 600; }}
  .stat.verified {{ color: var(--verified); }}
  .stat.unverified {{ color: var(--unverified); }}
  .stat-label {{ color: var(--muted); font-size: 0.85rem; }}
  table {{ width: 100%; border-collapse: collapse; font-size: 0.9rem; }}
  th, td {{ text-align: left; padding: 0.4rem 0.5rem; border-bottom: 1px solid var(--border); }}
  th {{ color: var(--muted); font-weight: 500; }}
  .bar-row {{ display: flex; align-items: center; gap: 0.75rem; margin-bottom: 0.6rem; }}
  .bar-label {{ width: 140px; flex-shrink: 0; font-size: 0.85rem; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }}
  .bar-track {{ flex: 1; background: var(--border); border-radius: 4px; height: 14px; overflow: hidden; }}
  .bar-fill {{ background: var(--accent); height: 100%; }}
  .bar-value {{ width: 130px; flex-shrink: 0; font-size: 0.8rem; color: var(--muted); text-align: right; }}
  .empty {{ color: var(--muted); font-style: italic; }}
  footer {{ margin-top: 2rem; color: var(--muted); font-size: 0.8rem; }}
</style>
</head>
<body>
  <h1>PaceProof report</h1>
  <div class="meta">source: {source} &middot; generated {generated_at}</div>

  <div class="grid">
    <div class="panel">
      <h2>Verified</h2>
      <div class="stat verified">{report['summary']['verified_count']}</div>
      <div class="stat-label">records with a valid Ed25519 signature</div>
      <table>{verified_units_html or '<tr><td class="empty">no verified compute totals</td></tr>'}</table>
    </div>
    <div class="panel">
      <h2>Unverified</h2>
      <div class="stat unverified">{report['summary']['unverified_count']}</div>
      <div class="stat-label">records excluded from verified totals</div>
      <table>{unverified_units_html or '<tr><td class="empty">no unverified compute totals</td></tr>'}</table>
    </div>
  </div>

  <div class="panel" style="margin-bottom:1.5rem;">
    <h2>Verified compute by provider</h2>
    {bars_html or '<div class="empty">no verified records</div>'}
  </div>

  <div class="panel">
    <h2>Why records were excluded</h2>
    {excluded_section_html}
  </div>

  <footer>{footer_text}</footer>
</body>
</html>
"""
